# Generated by Django 2.2.1 on 2021-08-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRecord',
            fields=[
                ('version_uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('task_uuid', models.CharField(max_length=50)),
                ('batch_seq', models.IntegerField()),
                ('batch_uuid', models.CharField(max_length=50)),
                ('batch_total_seq', models.IntegerField()),
                ('batch_back_status', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '批次回调记录',
                'db_table': 'batch_record',
            },
        ),
    ]
